### ISSUE TITLE
Favicon update required

### ISSUE THREAD

**Issue by tmsagarofficial** [jonbarron/website#170]
I want to point out that the current favicon for https://jonbarron.info is cropped up on the right edge; hence, changing this would help make sure it looks and feels nice to identify amongst a group of tabs.
Currently it is like this 
![image](https://github.com/jonbarron/website/assets/110724849/a11a8adf-b458-451a-a777-aad2089ed0db)
<img width="93" alt="image" src="https://github.com/jonbarron/website/assets/110724849/0b8b5c71-b693-4122-b992-5ce9c0e8f219">

Pls assign this issue to me so that I can start working in a fix for this issue @jonbarron

**Comment by jonbarron** [comment]
Oh heck yeah! That bothered me too, but wasn't an issue on Chrome on MacOS so I was ignoring it. Yeah if you can fix this that would be greatly appreciated!
