### ISSUE TITLE
Typo on your website (about the eclipse project)

### ISSUE THREAD

**Issue by kzhang2** [jonbarron/website#184]
Hi,

On your website, https://jonbarron.info/, you have Eclipse listed as being a CVPR 2023 paper, but the project page https://dorverbin.github.io/eclipse/ shows that it is a CVPR 2024 paper. I think ReconFusion should also be listed as CVPR 2024 paper, but it is currently listed on your main personal website as a CVPR 2023 paper? 

(coincidentally, today is the day of the total solar eclipse)

**Comment by jonbarron** [comment]
Lol thanks! Fixed.
